# Use root/example as user/password credentials
version: '3.4'

services:

  db:
    build:
      context: .
      network: host
    image: mysql
    volumes:
      # - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data:/var/lib/mysql
      # - ./secrets:/etc/certs
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: "zoolx"
      MYSQL_USER: "rust_driver"
      MYSQL_PASSWORD: "!xRL9^R7#*7MW=KsgxYXX%kENds-d?Hy"
      MYSQL_ROOT_PASSWORD: "KV1QN!Us|McNY_u47mp-E+0JKd8aAO3+"
    ports:
      - 3306:3306

  adminer:
    build:
      context: .
      network: host
    image: adminer
    restart: always
    ports:
      - 8080:8080