# Use root/example as user/password credentials
version: '3.4'

services:

  db:
    build:
      context: .
      network: host
    image: mysql
    volumes:
      - ./my.cnf:/etc/my.cnf
      - ./data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    build:
      context: .
      network: host
    image: adminer
    restart: always
    ports:
      - 8080:8080
