# Use root/example as user/password credentials
version: '3.4'

services:

  db:
    build:
      context: .
      network: host
    image: mysql/mysql-server
    volumes:
      - ./my.cnf:/etc/my.cnf
      - ./data:/var/lib/mysql
      - ./secrets:/etc/certs
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: "zoolx"
      MYSQL_USER: "rust_driver"
      MYSQL_PASSWORD: "!xRL9^R7#*7MW=KsgxYXX%kENds-d?Hy"
      MYSQL_ROOT_PASSWORD: "BQ3!8=5%Pf6rq#7xtLZg+FLRQmK65sq!MV!6*?U*DF"
    ports:
      - 3306:3306

  adminer:
    build:
      context: .
      network: host
    image: adminer
    restart: always
    ports:
      - 8080:8080
